import Image from 'next/image';
import React from 'react'

export const metadata = {
  title: "About | Create Next App",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div className=' mt-11 md:mt-28 flex justify-center'>
      <Image src={'https://plus.unsplash.com/premium_photo-1674406763863-b64be22c78a9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxmZWF0dXJlZC1waG90b3MtZmVlZHwxfHx8ZW58MHx8fHx8'} height={500} width={500} alt='neature'></Image>
    </div>
  )
}

export default About